# -*- coding: utf-8 -*-
"""Snippets: Importing libraries

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/snippets/importing_libraries.ipynb

# Importing a library that is not in Colaboratory

To import a library that's not in Colaboratory by default, you can use `!pip install` or `!apt-get install`.
"""

!pip install langchain openai langchain-community



pip install langchain openai
# langchain_llm_python_tool.py

from langchain.agents import initialize_agent, Tool
from langchain.agents.agent_types import AgentType
from langchain.tools.python.tool import PythonREPLTool
from langchain.llms import OpenAI
import os

# 🔑 Set your OpenAI API key
os.environ["OPENAI_API_KEY"] = "your-openai-api-key"

# 🔧 LLM (OpenAI)
llm = OpenAI(temperature=0)

# 🔧 Tool: Python REPL (executes Python code)
tools = [
    Tool(
        name="Python REPL",
        func=PythonREPLTool().run,
        description="Useful for math, programming, and calculations"
    )
]

# 🤖 Agent with LLM and REPL
agent = initialize_agent(
    tools,
    llm,
    agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION,
    verbose=True
)

# 🧪 Ask a question
question = "What is the derivative of x^2 + 3x + 2?"

response = agent.run(question)
print("\n🔹 Final Answer:\n", response)



!pip install matplotlib-venn

!apt-get -qq install -y libfluidsynth1

"""# Install 7zip reader [libarchive](https://pypi.python.org/pypi/libarchive)"""

# https://pypi.python.org/pypi/libarchive
!apt-get -qq install -y libarchive-dev && pip install -U libarchive
import libarchive

"""# Install GraphViz & [PyDot](https://pypi.python.org/pypi/pydot)"""

# https://pypi.python.org/pypi/pydot
!apt-get -qq install -y graphviz && pip install pydot
import pydot

"""# Install [cartopy](http://scitools.org.uk/cartopy/docs/latest/)"""

!pip install cartopy
import cartopy