# -*- coding: utf-8 -*-
"""Snippets: Importing libraries

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/snippets/importing_libraries.ipynb

# Importing a library that is not in Colaboratory

To import a library that's not in Colaboratory by default, you can use `!pip install` or `!apt-get install`.
"""

!pip install langchain openai langchain-community



# can_example.py

import can

def send_message(bus):
    message = can.Message(arbitration_id=0x123, data=[0x11, 0x22, 0x33], is_extended_id=False)
    try:
        bus.send(message)
        print(f"Message sent: {message}")
    except can.CanError:
        print("Message NOT sent")

def receive_message(bus):
    print("Listening for messages...")
    message = bus.recv(timeout=10)
    if message:
        print(f"Received message: {message}")
    else:
        print("No message received in 10 seconds.")

if __name__ == "__main__":
    # Using virtual CAN interface (vcan0) for testing
    bus = can.interface.Bus(channel='vcan0', bustype='socketcan')

    send_message(bus)
    receive_message(bus)



!pip install matplotlib-venn

!apt-get -qq install -y libfluidsynth1

"""# Install 7zip reader [libarchive](https://pypi.python.org/pypi/libarchive)"""

# https://pypi.python.org/pypi/libarchive
!apt-get -qq install -y libarchive-dev && pip install -U libarchive
import libarchive

"""# Install GraphViz & [PyDot](https://pypi.python.org/pypi/pydot)"""

# https://pypi.python.org/pypi/pydot
!apt-get -qq install -y graphviz && pip install pydot
import pydot

"""# Install [cartopy](http://scitools.org.uk/cartopy/docs/latest/)"""

!pip install cartopy
import cartopy