# -*- coding: utf-8 -*-
"""Snippets: Importing libraries

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/snippets/importing_libraries.ipynb

# Importing a library that is not in Colaboratory

To import a library that's not in Colaboratory by default, you can use `!pip install` or `!apt-get install`.
"""

!pip install langchain openai langchain-community



# google_translator.py

from googletrans import Translator

def translate_text(text, src='auto', dest='en'):
    translator = Translator()
    translation = translator.translate(text, src=src, dest=dest)
    return translation.text

if __name__ == "__main__":
    text = input("Enter text to translate: ")
    src_lang = input("Enter source language (or leave blank for auto): ") or 'auto'
    dest_lang = input("Enter destination language (e.g., en, fr, hi): ")

    try:
        translated = translate_text(text, src=src_lang, dest=dest_lang)
        print(f"Translated Text ({src_lang} ➝ {dest_lang}): {translated}")
    except Exception as e:
        print("Error during translation:", str(e))



!pip install matplotlib-venn

!apt-get -qq install -y libfluidsynth1

"""# Install 7zip reader [libarchive](https://pypi.python.org/pypi/libarchive)"""

# https://pypi.python.org/pypi/libarchive
!apt-get -qq install -y libarchive-dev && pip install -U libarchive
import libarchive

"""# Install GraphViz & [PyDot](https://pypi.python.org/pypi/pydot)"""

# https://pypi.python.org/pypi/pydot
!apt-get -qq install -y graphviz && pip install pydot
import pydot

"""# Install [cartopy](http://scitools.org.uk/cartopy/docs/latest/)"""

!pip install cartopy
import cartopy