# -*- coding: utf-8 -*-
"""Snippets: Importing libraries

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/snippets/importing_libraries.ipynb

# Importing a library that is not in Colaboratory

To import a library that's not in Colaboratory by default, you can use `!pip install` or `!apt-get install`.
"""

!pip install langchain openai langchain-community



# resume_analyzer_langchain.py

from langchain.llms import OpenAI
from langchain.chains import LLMChain
from langchain.prompts import PromptTemplate

llm = OpenAI()

prompt = PromptTemplate(
    input_variables=["resume"],
    template="""
Evaluate the following resume and provide suggestions to improve it. Also mention potential job roles for this candidate:\n\n{resume}
"""
)

analyzer_chain = LLMChain(llm=llm, prompt=prompt)

resume_text = """
John Doe, Python Developer with 2 years experience in web development.
Skilled in Django, Flask, and REST APIs. Seeking backend roles in tech.
"""

result = analyzer_chain.run(resume=resume_text)
print(result)



!pip install matplotlib-venn

!apt-get -qq install -y libfluidsynth1

"""# Install 7zip reader [libarchive](https://pypi.python.org/pypi/libarchive)"""

# https://pypi.python.org/pypi/libarchive
!apt-get -qq install -y libarchive-dev && pip install -U libarchive
import libarchive

"""# Install GraphViz & [PyDot](https://pypi.python.org/pypi/pydot)"""

# https://pypi.python.org/pypi/pydot
!apt-get -qq install -y graphviz && pip install pydot
import pydot

"""# Install [cartopy](http://scitools.org.uk/cartopy/docs/latest/)"""

!pip install cartopy
import cartopy